import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Providers } from "./providers";
import { PropsWithChildren } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Pokedex",
  description: "Generated by create next app",
};

export default function RootLayout({children}: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full">
      <body className={`${geistSans.className} h-full`}>
        <Providers>
          <div className="h-full">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
