import type { Metadata } from "next";
import { Lora, Geist } from "next/font/google";
import { Providers } from "./providers";
import { PropsWithChildren } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora"
})


export const metadata: Metadata = {
  title: "Pokedex",
  description: "Generated by create next app",
};

export default function RootLayout({children}: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.className}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
